version: "3"

services:
  opensearch-2.9.9:
    container_name: opensearch-2.9.9
    image: opensearchproject/opensearch
    environment:
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node"
    volumes:
      - os_data-2.9.9:/usr/share/opensearch/data
    ports:
      - 9201:9200
      - 9601:9600
    networks:
      - ckan-2.9.9

  publish-2.9.9:
    image: localhost:50579/publish:latest
    container_name: publish-2.9.9
    build:
      context: ./src/2.9.9/datagovuk_publish/
    env_file:
      - .env-2.9.9
    links:
      - db-2.9.9:db
      - opensearch-2.9.9:elasticsearch
      - redis-2.9.9:redis
      - ckan-2.9.9:ckan
    depends_on: 
      - db-2.9.9
      - opensearch-2.9.9
      - redis-2.9.9
    command: bash -c "bundle exec rails db:create && bundle exec rails db:schema:load && . ./bin/setup-docker.sh"
    volumes:
      - ./src/2.9.9/datagovuk_publish:/srv/app/datagovuk_publish
      - ./logs/2.9.9:/var/log/sidekiq
    networks:
      - ckan-2.9.9

  find-2.9.9:
    image: localhost:50579/find:latest
    container_name: find-2.9.9
    build:  
      context: ./src/2.9.9/datagovuk_find/
    env_file:
      - .env-2.9.9
    links:
      - opensearch-2.9.9:elasticsearch
    depends_on: 
      - opensearch-2.9.9
    command: bash -c "bin/yarn && ./bin/setup-docker.sh"
    volumes:
      - ./src/2.9.9/datagovuk_find:/srv/app/datagovuk_find
      - ./logs/2.9.9:/var/log/find
    networks:
      - ckan-2.9.9
    ports:
      - "4001:3000"

volumes:
  os_data-2.9.9:

networks:
    ckan-2.9.9:
        driver: bridge
