version: "3"

services:
  ckan-2.10:
    container_name: ckan-2.10
    image: ghcr.io/alphagov/ckan:2.10
    # build:
    #   context: ../
    #   dockerfile: docker/ckan/2.10.Dockerfile
    env_file:
      - .env-2.10
    links:
      - db-2.10:db
      - solr-2.10:solr
      - redis-2.10:redis
      - static-mock-harvest-source-2.10:static-mock-harvest-source
    ports:
      - "0.0.0.0:3003:3000"
    volumes:
      - ckan_storage-2.10:/var/lib/ckan
      - ./logs/2.10:/var/log/ckan
    depends_on: 
      - db-2.10
      - solr-2.10
      - redis-2.10
      - static-mock-harvest-source-2.10
    # command: bash -c "tail -f /dev/null"
    command: bash -c "ckan run --host 0.0.0.0"
    networks:
      - ckan-2.10

  pycsw-2.10:
    container_name: pycsw-2.10
    image: ghcr.io/alphagov/pycsw:2.6.1
    # image: localhost:61511/pycsw:2.6.1
    # build:
    #   context: ../
    #   dockerfile: docker/pycsw/2.6.1.Dockerfile
    env_file:
      - .env-2.10
    links:
      - db-2.10:db
      - solr-2.10:solr
      - redis-2.10:redis
      - ckan-2.10:ckan
    ports:
      - "0.0.0.0:8003:8000"
    depends_on: 
      - db-2.10
    # command: bash -c "tail -f /dev/null"
    command: bash -c "python /usr/lib/ckan/venv/src/pycsw/pycsw/wsgi.py"
    networks:
      - ckan-2.10

  db-2.10:
    container_name: db-2.10
    env_file:
      - .env-2.10
    build:
      context: ../
      dockerfile: docker/postgis/13-3.1.Dockerfile
    volumes:
      - pg_data-2.10:/var/lib/postgresql/data
    networks:
      - ckan-2.10

  solr-2.10:
    container_name: solr-2.10
    image: ghcr.io/alphagov/solr:2.10
    # build:
    #   context: ../
    #   dockerfile: docker/solr/2.10.Dockerfile
    ports:
      - "8983:8983"
    volumes:
      - solr_data-2.10:/opt/solr/server/solr/ckan/data
    networks:
      - ckan-2.10
  
  redis-2.10:
    container_name: redis-2.10
    image: redis:6.2.5-alpine3.14
    networks:
      - ckan-2.10
    volumes:
      - redis_data-2.10:/data

  nginx-2.10:
    container_name: nginx-2.10
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    links:
      - ckan-2.10:ckan
    ports:
      - 0.0.0.0:5001:80
    volumes:
      - ./logs/2.10:/var/log/nginx
    networks:
      - ckan-2.10

  static-mock-harvest-source-2.10:
    container_name: static-mock-harvest-source-2.10
    image: ghcr.io/alphagov/static-mock-harvest-source:2.10
    # image: localhost:61511/static-mock-harvest-source:2.10
    # build:
    #   context: ../
    #   dockerfile: docker/src/2.10/ckan-mock-harvest-sources/static/Dockerfile
    ports:
      - "11091:11088"
    volumes:
      - ./src/2.10/ckan-mock-harvest-sources/static/responses:/srv/responses
      - ./src/2.10/ckan-mock-harvest-sources/static/mock-third-party:/src/mock-third-party
    networks:
      - ckan-2.10

volumes:
  ckan_storage-2.10:
  pg_data-2.10:
  solr_data-2.10:
  redis_data-2.10:

networks:
  ckan-2.10:
      driver: bridge
